/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SchedulesImport } from './routes/schedules'
import { Route as CreateschedulesImport } from './routes/createschedules'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SchedulesRoute = SchedulesImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRoute,
} as any)

const CreateschedulesRoute = CreateschedulesImport.update({
  id: '/createschedules',
  path: '/createschedules',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/createschedules': {
      id: '/createschedules'
      path: '/createschedules'
      fullPath: '/createschedules'
      preLoaderRoute: typeof CreateschedulesImport
      parentRoute: typeof rootRoute
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createschedules': typeof CreateschedulesRoute
  '/schedules': typeof SchedulesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createschedules': typeof CreateschedulesRoute
  '/schedules': typeof SchedulesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/createschedules': typeof CreateschedulesRoute
  '/schedules': typeof SchedulesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createschedules' | '/schedules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createschedules' | '/schedules'
  id: '__root__' | '/' | '/createschedules' | '/schedules'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateschedulesRoute: typeof CreateschedulesRoute
  SchedulesRoute: typeof SchedulesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateschedulesRoute: CreateschedulesRoute,
  SchedulesRoute: SchedulesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/createschedules",
        "/schedules"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/createschedules": {
      "filePath": "createschedules.tsx"
    },
    "/schedules": {
      "filePath": "schedules.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
